# Generated by Django 4.2.14 on 2024-07-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("PARENT", "Parent"), ("CHILD", "Child")],
                        default="PARENT",
                        max_length=10,
                    ),
                ),
                ("demand", models.CharField(max_length=50)),
            ],
        ),
    ]
