# Generated by Django 4.2.14 on 2024-07-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domains", "0002_domain_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="average_salary",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
