# Generated by Django 4.2.14 on 2024-08-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0003_remove_skill_domains"),
        ("domains", "0003_domain_average_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="skills",
            field=models.ManyToManyField(related_name="domains", to="skills.skill"),
        ),
    ]
