# Generated by Django 4.2.14 on 2024-08-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0004_alter_skill_name"),
        ("domains", "0004_domain_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="domain",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="domains", to="skills.skill"
            ),
        ),
    ]
