# Generated by Django 4.2.14 on 2024-07-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("domains", "0001_initial"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration", models.DurationField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("EASY", "EASY"),
                            ("MEDIUM", "Medium"),
                            ("HARD", "HARD"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "domains",
                    models.ManyToManyField(related_name="courses", to="domains.domain"),
                ),
                (
                    "skills",
                    models.ManyToManyField(related_name="courses", to="skills.skill"),
                ),
            ],
        ),
    ]
