# Generated by Django 4.2.14 on 2024-07-29 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("domains", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("EASY", "EASY"),
                            ("MEDIUM", "Medium"),
                            ("HARD", "HARD"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "courses",
                    models.ManyToManyField(related_name="courses", to="courses.course"),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_schema",
                        to="domains.domain",
                    ),
                ),
            ],
        ),
    ]
