# Generated by Django 4.2.14 on 2024-07-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anims", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="anim",
            name="age",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
