# Generated by Django 4.2.14 on 2024-07-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("domains", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("PROGRAMING", "Programing"), ("SOFT", "Soft")],
                        default="PROGRAMING",
                        max_length=20,
                    ),
                ),
                (
                    "domains",
                    models.ManyToManyField(related_name="domains", to="domains.domain"),
                ),
            ],
        ),
    ]
